---
- hosts: all
  gather_facts: no
  connection: local
   

  tasks:
  
     - name: return next available IP address for network 10.80.100.0/22
       set_fact:
         ipaddr: "{{ lookup('nios_next_ip', '10.80.100.0/22', provider={'ssl_verify': 'no', 'wapi_version': '2.1', 'host': 'nios_host', 'username': 'nios_username', 'password': 'nios_password' }) }}"

