---
- hosts: all
  gather_facts: no
  connection: local



  tasks:

     - debug: var=Fortimgr_user
     - debug: var=Fortimgr_pass

     
     
     
#     - name: CREATE SCRIPT
#       fmgr_script:
#         host: "{{inventory_hostname}}"
#         username: "{{ Fortimgr_user }}"
#         password: "{{ Fortimgr_pass }}"
#         adom: "Stations"
#         script_name: "TestScript"
#         script_type: "cli"
#         script_target: "remote_device"
#         script_description: "Create by Ansible"
#         script_content: "get system status"
#         state: "present"

     - name: ADD IPv4 IP ADDRESS OBJECT
       fmgr_fwobj_address:
         host: "{{ inventory_hostname }}"
         username: "{{ Fortimgr_user }}"
         password: "{{ Fortimgr_pass }}"
         ipv4: "ipmask"
         ipv4addr: "2.2.2.2/32"
         name: "ansible_v4Obj"
         comment: "Created by Ansible"
         color: "6"
